apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-arm
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-arm
  template:
    metadata:
      labels:
        app: nginx-arm
    spec:
      nodeSelector:
        arch: arm64
        role: workload
      tolerations:
        - key: "karpenter.sh/provisioned"
          operator: "Equal"
          value: "arm64"
          effect: "NoSchedule"
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80