apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-spot
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-spot
  template:
    metadata:
      labels:
        app: nginx-spot
    spec:
      nodeSelector:
        role: spot
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80

